Blog,SV1, v1, SV2, v2,SV3, v3
 http://liveselfsufficient.com,AffluentInfluential.GreenLiving,6,Lifestyle.HealthFitnessDiet,3,AffluentInfluential.Luxury.FoodWine,3
http://1sovereignindividualpress.wordpress.com,Blog_Does_Not_Exist,7,,,,
http://1winedude.blogspot.com/,AffluentInfluential.Luxury.FoodWine,10,,,,
http://24-7style.com/serendipity/,Lifestyle.BeautyFashion.ShoppingFashion,7,,,,
http://247moms.blogspot.com/,Lifestyle.ParentingFamily,7,AffluentInfluential.GeneralInterest,2,,
http://2hood4hollywood.blogspot.com/,Entertainment.Celebrities.MoviesTelevisionMusic,6,Entertainment.Celebrities.Gossip,5,Lifestyle.BeautyFashion.ShoppingFashion,2
http://4entrepreneur.net,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,7,,,,
http://750ml.blogspot.com,AffluentInfluential.Luxury.FoodWine,7,,,,
http://7fatcow.com,Lifestyle,3,AffluentInfluential.GeneralInterest.Politics,3,Entertainment.Celebrities.MoviesTelevisionMusic,2
http://8download.blogspot.com/,Lifestyle.HealthFitnessDiet,6,Entertainment.Celebrities.MoviesTelevisionMusic,2,AffluentInfluential.Luxury.FoodWine,2
http://accidentalmommies.com,Lifestyle.ParentingFamily,7,,,,
http://acdc0805.blogspot.com/,Blog_Does_Not_Exist,4,Lifestyle.ParentingFamily,3,,
http://actionnooz.com/news,AffluentInfluential.GeneralInterest.Politics,7,Entertainment.Celebrities.Gossip,4,,
http://activitiesdirector.blogspot.com/,Lifestyle.HealthFitnessDiet,7,,,,
http://adhdguide.blogspot.com/,Lifestyle.HealthFitnessDiet,6,Lifestyle.ParentingFamily,2,,
http://adopttwoboys.blogspot.com/,Lifestyle.ParentingFamily,7,,,,
http://advocable.com,Technology.Consumer.Gaming,10,Technology.EnterpriseIT,6,,
http://afrobohemianchick.blogspot.com/,Lifestyle.BeautyFashion,4,AffluentInfluential.ArtsCraftsDesign,2,Lifestyle.HealthFitnessDiet,2
http://akashthoughts.blogspot.com/,Lifestyle,6,,,,
http://almost5.blogspot.com/,Lifestyle.ParentingFamily,6,,,,
http://americansoccerreader.com,Blog_Does_Not_Exist,7,,,,
http://animohosting.com/main,Lifestyle.ParentingFamily,5,AffluentInfluential.Luxury.FoodWine,3,AffluentInfluential.Travel,2
http://ankkit.blogspot.com/,Lifestyle,4,AffluentInfluential.GeneralInterest.Politics,4,Entertainment,2
http://appleaddiction.net,Technology.Consumer.Electronics,10,,,,
http://appruv.com,Technology.Consumer.Electronics,7,,,,
http://apronstringsaflutter.com,Lifestyle.ParentingFamily,7,,,,
http://arc4life.blogspot.com/,Lifestyle.HealthFitnessDiet,7,,,,
http://atberliner.blogspot.com/,Lifestyle.ParentingFamily,7,,,,
http://atlasshrugs2000.typepad.com/atlas_shrugs/,AffluentInfluential.GeneralInterest.Politics,6,,,,
http://atouchofblusher.blogspot.com/,Lifestyle.BeautyFashion.BeautyCosmetics,7,,,,
http://atregembo.blogspot.com/,Lifestyle.ParentingFamily,9,,,,
http://atypicalset.blogspot.com/,Entertainment.Celebrities.MoviesTelevisionMusic,5,AffluentInfluential.ArtsCraftsDesign,3,AffluentInfluential.GeneralInterest,2
http://augirl75.blogspot.com/,Lifestyle.ParentingFamily,7,,,,
http://babykeisha.blogspot.com/,Lifestyle.ParentingFamily,9,,,,
http://bagsnob.com/,Lifestyle.BeautyFashion.ShoppingFashion,6,AffluentInfluential.Luxury,4,Entertainment.Celebrities.Gossip,2
http://baldwinhouse.blogspot.com/,Lifestyle.ParentingFamily,9,,,,
http://baraksmusings.blogspot.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,6,AffluentInfluential.GeneralInterest.Politics,5,Technology,2
http://barroyo.blogspot.com/,Blog_Does_Not_Exist,3,Spam.Blog,3,,
http://barrys-wine.blogspot.com,AffluentInfluential.Luxury.FoodWine,7,,,,
http://beateen.com/blog2,Blog_Does_Not_Exist,4,Lifestyle.ParentingFamily,2,,
http://beauty-tyrant.blogspot.com/,Lifestyle.BeautyFashion.BeautyCosmetics,13,Lifestyle.BeautyFashion.ShoppingFashion,7,,
http://beauty411.typepad.com/my_weblog/,Lifestyle.BeautyFashion.BeautyCosmetics,8,Lifestyle.BeautyFashion.ShoppingFashion,5,,
http://behindblondiepark.com,Entertainment.Celebrities.Gossip,8,AffluentInfluential.GeneralInterest.Politics,3,Lifestyle.HealthFitnessDiet,2
http://belladia.typepad.com/bella_dia/,AffluentInfluential.ArtsCraftsDesign,5,Lifestyle.BeautyFashion.ShoppingFashion,4,,
http://bestantiagingskincare.blogspot.com/,Lifestyle.BeautyFashion.BeautyCosmetics,7,Lifestyle.ParentingFamily,3,Lifestyle.HealthFitnessDiet,2
http://bestclubmusic.net,Entertainment.Celebrities.MoviesTelevisionMusic,7,Technology,2,,
http://bestfreewareblog.com,Technology.EnterpriseIT,6,Technology.Consumer,3,,
http://bestpetsdogtraining.com,Lifestyle.ParentingFamily,7,,,,
http://beta.hacknmod.com,Technology.Consumer.Electronics,8,Technology.Consumer.Gaming,7,AffluentInfluential.ArtsCraftsDesign,2
http://betsyspage.blogspot.com/,AffluentInfluential.GeneralInterest.Politics,8,,,,
http://beyondnichemarketing.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,5,Technology.EnterpriseIT,3,,
http://blog.80percentmental.com/,Entertainment.Sports.CommercialSports,8,,,,
http://blog.contempomag.com,AffluentInfluential.GeneralInterest.Politics,7,Entertainment.Celebrities.Gossip,2,,
http://blog.hemmings.com,AffluentInfluential.Luxury.Automotive,5,Entertainment.Sports.AdventureOutdoorSports,2,Entertainment.Mens.Interest,2
http://blog.hisnameistimmy.com,AffluentInfluential.GeneralInterest.Politics,6,Lifestyle,2,,
http://blog.homebrewbeer.net/,AffluentInfluential.Luxury.FoodWine,5,,,,
http://blog.largeheartedboy.com/,Entertainment.Celebrities.MoviesTelevisionMusic,8,,,,
http://blog.nikhil.co.in/,Lifestyle,5,AffluentInfluential.GeneralInterest.Politics,2,,
http://blog.parentsovernight.com,Lifestyle.ParentingFamily,8,Lifestyle.HealthFitnessDiet,2,,
http://blog.ragingtech.com,Technology.Consumer.Electronics,13,Technology.EnterpriseIT,6,,
http://blog.sensiblemarketing.biz,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,Spam.Blog,2,Technology,2
http://blog.snhparents.com,Lifestyle.ParentingFamily,8,,,,
http://blog.stickis.com,Technology.EnterpriseIT,3,Lifestyle,2,AffluentInfluential.GeneralInterest.Politics,2
http://blog.taragana.com/,Technology.Consumer.Electronics,8,Technology.EnterpriseIT,7,,
http://blog.yamobile.mobi/,Blog_Does_Not_Exist,7,,,,
http://blogbadly.com,Technology.EnterpriseIT,6,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,,
http://bloggersschool.blogspot.com/,Technology.Consumer,6,Technology.EnterpriseIT,5,,
http://bloggingus.com,AffluentInfluential.Travel,5,Entertainment.Sports.AdventureOutdoorSports,2,,
http://blogkinnetic.blogspot.com/,AffluentInfluential.GeneralInterest.Politics,6,Technology,5,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3
http://blogofhilarity.com,Entertainment.Mens.Interest,4,Entertainment.Celebrities.Gossip,3,Entertainment.Celebrities.MoviesTelevisionMusic,2
http://blogs.feedburner.com/feedburner/,Technology.Consumer.Electronics,10,Technology.EnterpriseIT,5,,
http://blogxilla.com/blog3,Entertainment.Celebrities.MoviesTelevisionMusic,6,Lifestyle.HealthFitnessDiet,3,,
http://blurnot.blogspot.com/,Technology.Consumer.Electronics,8,Technology.EnterpriseIT,3,,
http://bombshellbeauty.blogspot.com/,Lifestyle.BeautyFashion.BeautyCosmetics,7,Lifestyle.BeautyFashion.ShoppingFashion,6,,
http://bouhammer.com/wordpress,AffluentInfluential.GeneralInterest.Politics,7,,,,
http://brahsome.com/,Entertainment.Sports.CommercialSports,7,Entertainment.Mens.Interest,4,Entertainment.Celebrities.MoviesTelevisionMusic,3
http://brainsickpolitic.com,AffluentInfluential.GeneralInterest.Politics,4,Blog_Does_Not_Exist,3,,
http://brajeshwar.com,Technology.EnterpriseIT,7,Technology.Consumer,3,,
http://brownsugar28.blogspot.com/,Lifestyle.ParentingFamily,7,Entertainment.Celebrities,4,AffluentInfluential.GeneralInterest.Politics,3
http://bruces-linux-it.blogspot.com/,Technology.EnterpriseIT,8,Technology.Consumer,5,,
http://buzzblogz.blogspot.com/,Blog_Does_Not_Exist,3,Spam.Blog,3,,
http://buzzlogiccommunitytest.blogspot.com/,Blog_Does_Not_Exist,4,Spam.Blog,2,,
http://buzzmember1.blogspot.com/,Technology.Consumer.Gaming,6,Entertainment.Mens.Interest,2,,
http://buzzmember2.blogspot.com/,Technology.Consumer.Gaming,6,,,,
http://by-la.com,AffluentInfluential.Travel,5,Lifestyle.ParentingFamily,4,AffluentInfluential.GeneralInterest,2
http://caribbeanwaters.blogspot.com/,AffluentInfluential.Travel,6,Lifestyle,2,,
http://cartoonreality.blogspot.com/,Entertainment.Celebrities.MoviesTelevisionMusic,7,,,,
http://cartoonrealityqa2.blogspot.com/,Entertainment.Celebrities.MoviesTelevisionMusic,6,Lifestyle,2,,
http://cat-iim-mba.blogspot.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,6,AffluentInfluential.GeneralInterest.Politics,6,Lifestyle,3
http://catholicreligiontoday.blogspot.com/,Lifestyle.HealthFitnessDiet,6,,,,
http://celebglitz.com,Entertainment.Celebrities.Gossip,6,Entertainment.Celebrities.MoviesTelevisionMusic,3,,
http://celebrifi.com/,Entertainment.Celebrities.Gossip,7,,,,
http://celebrity.rightpundits.com,Entertainment.Celebrities.Gossip,6,Entertainment.Celebrities.MoviesTelevisionMusic,3,,
http://chezberliners.blogspot.com/,Lifestyle.ParentingFamily,3,AffluentInfluential.Luxury.FoodWine,3,Lifestyle.HealthFitnessDiet,2
http://chezberlinersqa2.blogspot.com/,AffluentInfluential.Luxury.FoodWine,5,Lifestyle.ParentingFamily,2,,
http://chicagoboyz.net,AffluentInfluential.GeneralInterest.Politics,7,Entertainment,3,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3
http://chicagoweekendfun.com,Entertainment.Sports.CommercialSports,5,Lifestyle.HealthFitnessDiet,4,AffluentInfluential.Travel,2
http://chinaadopttalk.com/,Lifestyle.ParentingFamily,7,,,,
http://chocolatedogblog.com/,Lifestyle.BeautyFashion,5,AffluentInfluential,2,,
http://cod4source.com,Technology.Consumer.Gaming,8,,,,
http://comicsidontunderstand.com/wordpress/,Entertainment,6,,,,
http://compassionatebadger.blogspot.com/,Lifestyle,5,AffluentInfluential.GeneralInterest.Politics,3,,
http://constructivegrumpiness.com/cg-home/,Blog_Does_Not_Exist,6,,,,
http://controlaltdelete.tv,Technology.Consumer.Electronics,7,Technology.EnterpriseIT,4,,
http://copiousdissent.blogspot.com/,AffluentInfluential.GeneralInterest.Politics,8,,,,
http://crabbieshollywood.blogspot.com/,Entertainment.Celebrities.Gossip,8,Entertainment.Celebrities.MoviesTelevisionMusic,3,,
http://crenk.com,Technology.Consumer,7,Technology.EnterpriseIT,6,,
http://crotchetyoldfan.wordpress.com,Entertainment.Celebrities.MoviesTelevisionMusic,7,AffluentInfluential.GeneralInterest,2,Lifestyle,2
http://cuzoogle.com/,Entertainment.Sports.CommercialSports,9,Entertainment.Mens.Interest,5,Entertainment.Celebrities.MoviesTelevisionMusic,4
http://cyanatrendland.com,Lifestyle.BeautyFashion.ShoppingFashion,6,Lifestyle.BeautyFashion.BeautyCosmetics,4,AffluentInfluential.ArtsCraftsDesign,3
http://cybersurge.org,Technology.Consumer.Electronics,9,,,,
http://daily-soft.blogspot.com/,Technology.Consumer.Electronics,5,Technology.EnterpriseIT,4,,
http://dailypundit.com,AffluentInfluential.GeneralInterest.Politics,6,,,,
http://dailytechtalk.com,Technology.Consumer.Electronics,8,Technology.EnterpriseIT,4,,
http://daisythecurlycat.blogspot.com/,Lifestyle,5,,,,
http://datingdatingall-things-dating.blogspot.com/,Lifestyle,6,,,,
http://deafmomworld.com/hp_wordpress,Blog_Does_Not_Exist,4,Spam.Blog,2,,
http://deanbrowski.com,Entertainment.Sports.CommercialSports,6,,,,
http://dechenlau.com,Technology.Consumer.Electronics,3,Spam.Blog,2,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2
http://deepcenterfield.wordpress.com,Entertainment.Sports.CommercialSports,6,AffluentInfluential.GeneralInterest.Politics,5,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3
http://devilliers.wordpress.com,Lifestyle.BeautyFashion.BeautyCosmetics,5,Lifestyle.HealthFitnessDiet,3,,
http://diningsmart.com,Lifestyle.HealthFitnessDiet,6,AffluentInfluential.Luxury.FoodWine,4,,
http://discoveringhair.com/blog,Lifestyle.BeautyFashion.BeautyCosmetics,7,,,,
http://distractible.org/,Lifestyle.HealthFitnessDiet,6,AffluentInfluential.GeneralInterest.Politics,4,,
http://distressedderma.com,Lifestyle.BeautyFashion.BeautyCosmetics,10,Lifestyle.BeautyFashion.ShoppingFashion,4,,
http://dividendgrowth.blogspot.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,7,,,,
http://doodaddy.net,Lifestyle.ParentingFamily,7,,,,
http://dormscout.com,Entertainment.Celebrities.MoviesTelevisionMusic,5,Lifestyle,4,AffluentInfluential.GeneralInterest.Politics,4
http://dougist.com,AffluentInfluential.GeneralInterest.Politics,5,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3,Technology,2
http://download-songs.in/,Entertainment.Celebrities.MoviesTelevisionMusic,4,Spam.Blog,2,,
http://dreamdogsart.typepad.com/art/,AffluentInfluential.ArtsCraftsDesign,5,Lifestyle.ParentingFamily,3,AffluentInfluential.GeneralInterest,2
http://duplicatetestbz.blogspot.com/,Blog_Does_Not_Exist,7,,,,
http://dvictorio.blogspot.com/,Lifestyle,4,Entertainment.Sports.CommercialSports,3,Technology.Consumer,2
http://easybreezyufizi.blogspot.com/,Blog_Does_Not_Exist,5,,,,
http://eclipsemagazine.com,Entertainment.Celebrities.MoviesTelevisionMusic,6,Technology.Consumer,2,,
http://educatorslife.blogspot.com/,Lifestyle,4,AffluentInfluential.Travel,2,,
http://ejobtips.blogspot.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,5,Technology.EnterpriseIT,2,,
http://elitefoods.blogspot.com/,AffluentInfluential.Luxury.FoodWine,4,Lifestyle.HealthFitnessDiet,3,,
http://entropiamining.blogspot.com/,Technology.Consumer.Gaming,5,AffluentInfluential.GreenLiving,3,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2
http://epicwaves.blogspot.com/,Entertainment.Sports.AdventureOutdoorSports,3,Lifestyle.HealthFitnessDiet,3,,
http://escapebrooklyn.blogspot.com/,Lifestyle.BeautyFashion.ShoppingFashion,4,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3,AffluentInfluential.Travel,2
http://esha.awardspace.com,AffluentInfluential.GeneralInterest.Politics,6,Technology.EnterpriseIT,4,,
http://ever-after.org,Lifestyle.HealthFitnessDiet,2,AffluentInfluential.GeneralInterest.Politics,2,Lifestyle.BeautyFashion.BeautyCosmetics,2
http://everythinginorder.wordpress.com,Lifestyle,7,,,,
http://facecandy.blogspot.com/,Lifestyle.BeautyFashion.BeautyCosmetics,6,Lifestyle.BeautyFashion.ShoppingFashion,6,,
http://fareastgizmos.com/,Technology.Consumer.Electronics,9,Technology.Consumer.Gaming,4,,
http://fatlossdoneez.blogspot.com/,Lifestyle.HealthFitnessDiet,7,,,,
http://fenwaywest.blogspot.com/,Entertainment.Sports.CommercialSports,7,,,,
http://fertilityfile.com,Lifestyle.HealthFitnessDiet,6,Lifestyle.ParentingFamily,5,,
http://firefinance.blogspot.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,6,Lifestyle.ParentingFamily,3,AffluentInfluential.GeneralInterest.Politics,2
http://fireinmybrain.blogspot.com/,Lifestyle.HealthFitnessDiet,7,Lifestyle.ParentingFamily,2,,
http://flashinglights.typepad.com/flashinglights/,Entertainment.Celebrities.Gossip,7,Lifestyle.BeautyFashion.ShoppingFashion,5,Lifestyle.BeautyFashion.BeautyCosmetics,3
http://flushhard.blogspot.com/,Lifestyle,3,Entertainment.Mens.Interest,3,AffluentInfluential.Luxury.Automotive,2
http://foodfightblog.blogspot.com/,AffluentInfluential.Luxury.FoodWine,5,Lifestyle.HealthFitnessDiet,3,,
http://frenchietink.com,Lifestyle,6,,,,
http://frequentlyfeline.blogspot.com/,Lifestyle,5,,,,
http://freybird.blogspot.com/,Entertainment.Sports.AdventureOutdoorSports,5,Lifestyle.HealthFitnessDiet,2,,
http://funkyblackchick.com,Lifestyle.BeautyFashion.ShoppingFashion,4,Lifestyle.BeautyFashion.BeautyCosmetics,4,Entertainment.Celebrities.Gossip,3
http://fussypants.typepad.com/whatsmartmommiesknow/,Lifestyle.ParentingFamily,7,Lifestyle.BeautyFashion.BeautyCosmetics,3,,
http://fvsoft.blogspot.com/,Technology.Consumer.Electronics,5,Technology.EnterpriseIT,4,,
http://gaboink.net,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,5,Technology.EnterpriseIT,4,Technology.Consumer,3
http://gamingoutpost.com,Technology.Consumer.Gaming,7,,,,
http://gatewaypundit.blogspot.com/,AffluentInfluential.GeneralInterest.Politics,7,Entertainment.Celebrities,2,,
http://getanewbrowser.com,Technology.Consumer.Electronics,16,Technology.EnterpriseIT,7,,
http://ghettofabu.blogspot.com/,Entertainment.Celebrities.Gossip,6,Entertainment.Celebrities.MoviesTelevisionMusic,4,,
http://gicharts.blogspot.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,7,,,,
http://girlgloss.com,Lifestyle.BeautyFashion.BeautyCosmetics,7,,,,
http://girlsgonechild.blogspot.com/,Lifestyle.ParentingFamily,8,Lifestyle.BeautyFashion,4,,
http://globaljavafaq.blogspot.com/,Technology.EnterpriseIT,6,Technology.Consumer.Electronics,4,,
http://goatechno.blogspot.com/,Technology.Consumer.Electronics,7,Technology.EnterpriseIT,3,,
http://goinglikesixty.com,Lifestyle,4,Entertainment.Mens.Interest,3,AffluentInfluential.GeneralInterest.Politics,2
http://gooddogfood.org,Lifestyle.HealthFitnessDiet,5,AffluentInfluential.GeneralInterest,2,AffluentInfluential.Luxury.FoodWine,2
http://goodgolftipsforbeginners.blogspot.com/,Entertainment.Sports.AdventureOutdoorSports,6,Entertainment.Sports.CommercialSports,5,,
http://gravyandbiscuits.com,Entertainment.Celebrities.MoviesTelevisionMusic,4,Blog_Does_Not_Exist,3,Entertainment.Celebrities.Gossip,3
http://greatwebguy.com,Technology.Consumer.Electronics,10,Technology.EnterpriseIT,4,,
http://grocerymama.typepad.com/grocery_mama/,Lifestyle.ParentingFamily,5,Lifestyle.HealthFitnessDiet,3,,
http://gurlytalkhere.blogspot.com/,Blog_Does_Not_Exist,7,,,,
http://haze-workathome.blogspot.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,5,Lifestyle,3,Spam.Blog,2
http://heaven-places.com/,AffluentInfluential.Travel,7,Lifestyle,2,,
http://hellerdrone.wordpress.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,7,Lifestyle,2,,
http://hild1thoughts.blogspot.com/,Blog_Does_Not_Exist,5,Lifestyle,2,,
http://howdoyoudate.blogspot.com/,Lifestyle.ParentingFamily,6,,,,
http://howtogetpregnantsite.info,Lifestyle.ParentingFamily,7,,,,
http://hq.andrewshuttleworth.com/hq/,Technology.EnterpriseIT,6,Technology.Consumer,6,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2
http://hyveup.blogspot.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3,Blog_Does_Not_Exist,2,,
http://iafresh.com/fresh,Entertainment.Celebrities.MoviesTelevisionMusic,6,Lifestyle.BeautyFashion,4,AffluentInfluential.GeneralInterest.Politics,3
http://ifitshipitshere.blogspot.com/,AffluentInfluential.ArtsCraftsDesign,4,Lifestyle.BeautyFashion.ShoppingFashion,3,AffluentInfluential.Luxury,2
http://immoralmatriarch.com,AffluentInfluential.GeneralInterest.Politics,4,Lifestyle,3,Entertainment,2
http://imwithjoe.com,Lifestyle,4,Technology.EnterpriseIT,3,Technology.Consumer,3
http://indianautosblog.com,AffluentInfluential.Luxury.Automotive,7,Entertainment.Mens.Interest,3,,
http://infodotnet.blogspot.com/,Technology.Consumer.Electronics,9,Technology.EnterpriseIT,5,,
http://iphonefreakz.com,Technology.Consumer.Electronics,7,,,,
http://islamcrunch.com,Lifestyle,4,Entertainment,2,AffluentInfluential.GeneralInterest.Politics,2
http://isleng.blogspot.com/,Entertainment.Celebrities.MoviesTelevisionMusic,7,Lifestyle,2,,
http://isleng17.blogspot.com/,Lifestyle.ParentingFamily,7,,,,
http://iyercooks.blogspot.com/,Lifestyle.HealthFitnessDiet,5,AffluentInfluential.Luxury.FoodWine,3,,
http://jackbook.com,Entertainment,3,Technology.Consumer.Electronics,3,Spam.Blog,2
http://jadonian-gamer.blogspot.com/,Technology.Consumer.Gaming,7,,,,
http://jadonian.blogspot.com/,Technology.Consumer.Gaming,6,,,,
http://janetgardner.blogspot.com/,Lifestyle.HealthFitnessDiet,6,Entertainment,2,,
http://jfdnetworks.blogspot.com/,Technology.EnterpriseIT,7,Technology.Consumer,5,,
http://joeanderson.co.uk/blog,Technology.Consumer.Electronics,9,Technology.Consumer.Gaming,8,Technology.EnterpriseIT,4
http://jokesmedia.com,Entertainment,7,,,,
http://jta-web.com/amy,Lifestyle.ParentingFamily,7,,,,
http://juicedsportsblog.com,Entertainment.Sports.CommercialSports,6,,,,
http://justabilities.blogspot.com/,Lifestyle.HealthFitnessDiet,6,Lifestyle.ParentingFamily,4,,
http://justcreativedesign.com,Technology.EnterpriseIT,3,AffluentInfluential.ArtsCraftsDesign,3,,
http://kalil4u.blogspot.com/,Technology.EnterpriseIT,6,,,,
http://kamalkumar.com.np,AffluentInfluential.GeneralInterest.Politics,5,,,,
http://kartikbuzz.blogspot.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,Spam.Blog,2,Lifestyle.ParentingFamily,2
http://kgar-arthouse.blogspot.com/,Entertainment.Celebrities.MoviesTelevisionMusic,3,AffluentInfluential.Travel,2,AffluentInfluential.ArtsCraftsDesign,2
http://kimballtalk.blogspot.com/,AffluentInfluential.GeneralInterest.Politics,6,Entertainment,4,Lifestyle.ParentingFamily,3
http://kimdutoit.com/index.php,Blog_Does_Not_Exist,7,,,,
http://kittybradshaw.com,Lifestyle.BeautyFashion.BeautyCosmetics,4,AffluentInfluential.GeneralInterest.Politics,3,Entertainment.Celebrities.MoviesTelevisionMusic,2
http://kls-familytime.blogspot.com/,Lifestyle.ParentingFamily,7,,,,
http://komicwords.com,Entertainment.Celebrities.MoviesTelevisionMusic,7,Technology.Consumer,2,,
http://la-oc-foodie.blogspot.com,AffluentInfluential.Luxury.FoodWine,6,Lifestyle.HealthFitnessDiet,3,,
http://labnol.blogspot.com/,Technology.EnterpriseIT,6,,,,
http://ladyjava.javaura.com/,Lifestyle.BeautyFashion.BeautyCosmetics,7,Lifestyle.BeautyFashion.ShoppingFashion,7,Entertainment.Celebrities.MoviesTelevisionMusic,3
http://lakeminnetonkaliberty.blogspot.com/,AffluentInfluential.GeneralInterest.Politics,7,,,,
http://laout.wordpress.com,Lifestyle,6,AffluentInfluential.GeneralInterest.Politics,4,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3
http://larrybrownsports.com,Entertainment.Sports.CommercialSports,7,,,,
http://legalprincess.blogspot.com/,Lifestyle,5,,,,
http://libertarianrepublican.blogspot.com/,AffluentInfluential.GeneralInterest.Politics,9,,,,
http://likastarr.com,Entertainment.Celebrities.Gossip,4,Lifestyle.ParentingFamily,3,AffluentInfluential.GeneralInterest.Politics,3
http://limitedcleverness.blogspot.com/,Lifestyle.ParentingFamily,7,,,,
http://linkbuildingbible.com,Technology.EnterpriseIT,6,,,,
http://littlemissattila.mu.nu/,AffluentInfluential.GeneralInterest.Politics,6,Lifestyle,3,,
http://live-high-on.blogspot.com/,Technology.Consumer.Electronics,7,,,,
http://lostinlimaohio.blogspot.com/,AffluentInfluential.GeneralInterest.Politics,6,,,,
http://lucky-six.blogspot.com/,AffluentInfluential.GeneralInterest.Politics,10,Technology.Consumer,6,Lifestyle,3
http://lulu-momblog.blogspot.com/,Lifestyle.ParentingFamily,7,Lifestyle.HealthFitnessDiet,3,,
http://mabuhayihs.wordpress.com,Entertainment,3,AffluentInfluential.GeneralInterest,3,Lifestyle,3
http://madgaywedding.blogspot.com/,Lifestyle.ParentingFamily,7,AffluentInfluential.GeneralInterest.Politics,2,,
http://maestromotif.com,Entertainment.Celebrities.MoviesTelevisionMusic,7,Entertainment.Celebrities.Gossip,2,,
http://makefun.cn,Entertainment,4,AffluentInfluential.Travel,2,Lifestyle,2
http://maknalivingonline.blogspot.com/,Blog_Does_Not_Exist,7,,,,
http://manitouheights.com/blog,Blog_Does_Not_Exist,6,,,,
http://manodogs.blogspot.com/,Entertainment.Celebrities.MoviesTelevisionMusic,8,Entertainment.Celebrities.Gossip,4,,
http://marmarwelter.blogspot.com/,Lifestyle,5,AffluentInfluential.GeneralInterest.Politics,2,,
http://masontechbeat.blogspot.com/,Technology.Consumer.Electronics,11,Technology.EnterpriseIT,4,,
http://mattylounge.blogspot.com/,Lifestyle,6,Entertainment.Celebrities.MoviesTelevisionMusic,4,,
http://measuringhistory.com/blog,Blog_Does_Not_Exist,4,Lifestyle,2,,
http://mentalmommy.blogspot.com/,Lifestyle.ParentingFamily,6,Lifestyle.HealthFitnessDiet,3,,
http://messagetestbz.blogspot.com/,Blog_Does_Not_Exist,7,,,,
http://michaeljohnsonfreedomandprosperity.blogspot.com/,AffluentInfluential.GeneralInterest.Politics,6,,,,
http://michiganrawfoodblog.blogspot.com/,Lifestyle.HealthFitnessDiet,5,AffluentInfluential.Luxury.FoodWine,3,,
http://miconservative.wordpress.com,AffluentInfluential.GeneralInterest.Politics,7,,,,
http://milehimama.blogspot.com/,Lifestyle.ParentingFamily,6,Lifestyle.HealthFitnessDiet,4,Lifestyle.BeautyFashion.ShoppingFashion,2
http://milenabuzz.blogspot.com/,Blog_Does_Not_Exist,6,,,,
http://military.rightpundits.com,AffluentInfluential.GeneralInterest.Politics,7,Entertainment.Celebrities.Gossip,3,,
http://mindtrapeze.blogspot.com/,Blog_Does_Not_Exist,7,,,,
http://mommyrevenue.com,Lifestyle.ParentingFamily,4,Technology,3,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3
http://momskitchencooking.blogspot.com/,Lifestyle.HealthFitnessDiet,3,Lifestyle.ParentingFamily,3,AffluentInfluential.Luxury.FoodWine,3
http://moneysavingmami.blogspot.com/,Lifestyle.ParentingFamily,4,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3,,
http://moneytreetips.blogspot.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,,,,
http://moolahblog.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,6,AffluentInfluential.GeneralInterest.Politics,3,,
http://mothertoson.blogspot.com/,Lifestyle.ParentingFamily,7,,,,
http://movieporium.blogspot.com/,Entertainment.Celebrities.MoviesTelevisionMusic,7,,,,
http://msjuliesartschool.blogspot.com/,AffluentInfluential.ArtsCraftsDesign,5,Lifestyle.ParentingFamily,3,,
http://mssinglemama.com,Lifestyle.ParentingFamily,8,,,,
http://musicbusinesspage.com,Entertainment.Celebrities.MoviesTelevisionMusic,7,,,,
http://mwcfootball.wordpress.com,Entertainment.Sports.CommercialSports,7,,,,
http://mycrazylifewithatoddler.blogspot.com/,Lifestyle.ParentingFamily,8,,,,
http://mygoodcents.net,Lifestyle.ParentingFamily,4,Lifestyle.BeautyFashion.ShoppingFashion,4,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3
http://neonlimelight.com,Entertainment.Celebrities.MoviesTelevisionMusic,10,Entertainment.Celebrities.Gossip,6,,
http://net-savvy.com/executive/,Technology.EnterpriseIT,4,Technology.Consumer,4,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2
http://newestindustry.org/,Technology.EnterpriseIT,5,Lifestyle,3,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2
http://nfttu.blogspot.com ,Technology,5,Entertainment.Mens.Interest,2,,
http://nihilo0.blogspot.com/,AffluentInfluential.GeneralInterest.Politics,6,,,,
http://nogoodforme.filmstills.org/,Lifestyle.BeautyFashion.ShoppingFashion,7,Lifestyle.HealthFitnessDiet,4,,
http://norcalham.blogspot.com/,Technology.EnterpriseIT,5,Entertainment.Celebrities.MoviesTelevisionMusic,2,,
http://nspeaks.com,Technology.Consumer,5,,,,
http://nuxmatics.com,Technology.EnterpriseIT,3,,,,
http://nyystadiuminsider.com/,Entertainment.Sports.CommercialSports,7,,,,
http://observin.com,Technology.Consumer,6,AffluentInfluential.ArtsCraftsDesign,3,,
http://okayfinedammit.com,Lifestyle.ParentingFamily,7,AffluentInfluential.GeneralInterest,2,,
http://olympicsbeijing2008-paul.blogspot.com/,Entertainment.Sports.CommercialSports,6,,,,
http://onemillionpetpics.com,Lifestyle.ParentingFamily,7,,,,
http://oneutah.org,AffluentInfluential.GeneralInterest.Politics,6,,,,
http://onlinejournalismblog.com,AffluentInfluential.GeneralInterest.Politics,8,,,,
http://ooolala.blog.co.in,Blog_Does_Not_Exist,3,Spam.Blog,2,AffluentInfluential,2
http://pajamamom.com,Lifestyle.ParentingFamily,6,Lifestyle.BeautyFashion,2,Lifestyle.HealthFitnessDiet,2
http://pcsoftwarez.blogspot.com/,Technology.Consumer.Gaming,6,Entertainment.Celebrities.MoviesTelevisionMusic,2,,
http://perezhilton.com,Entertainment.Celebrities.Gossip,8,Entertainment.Celebrities.MoviesTelevisionMusic,3,,
http://perezhilton.com/,Entertainment.Celebrities.Gossip,9,Entertainment.Celebrities.MoviesTelevisionMusic,4,,
http://perezrevenge.com,Entertainment.Celebrities.Gossip,6,Entertainment.Celebrities.MoviesTelevisionMusic,5,,
http://peterpanandfamily.blogspot.com/,Lifestyle.ParentingFamily,7,,,,
http://photosonweb.blogspot.com/,Entertainment.Celebrities.Gossip,7,,,,
http://pickuppodcast.com/blogv2,Lifestyle,5,Entertainment.Mens.Interest,4,,
http://pinkbunnynewsgossiptips.blogspot.com/,Entertainment.Celebrities.Gossip,7,Entertainment.Celebrities.MoviesTelevisionMusic,2,,
http://plotdog.com,Lifestyle,4,AffluentInfluential.ArtsCraftsDesign,2,Entertainment.Celebrities.MoviesTelevisionMusic,2
http://plr-income.blogspot.com/,Technology.EnterpriseIT,4,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,Technology.Consumer,3
http://poetrynjewels.blogspot.com/,AffluentInfluential.ArtsCraftsDesign,5,Lifestyle.BeautyFashion.BeautyCosmetics,4,,
http://pointlessbanter.net,Entertainment.Celebrities.MoviesTelevisionMusic,6,Entertainment.Celebrities.Gossip,4,Lifestyle,3
http://powerandstilettos.blogspot.com/,Lifestyle.ParentingFamily,5,AffluentInfluential.GeneralInterest.Politics,4,AffluentInfluential.ArtsCraftsDesign,2
http://powersuccessmarketing.blogspot.com/,Technology.EnterpriseIT,5,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,,
http://pradeepchakraborty.blogspot.com/,Technology.EnterpriseIT,4,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3,,
http://ptmoney.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,7,,,,
http://random-related.com/random,Entertainment.Celebrities.Gossip,7,AffluentInfluential.GeneralInterest.Politics,2,,
http://readerszone.com,Technology.Consumer.Electronics,7,Technology.EnterpriseIT,3,Entertainment,2
http://realtechnews.com/,Technology.Consumer.Electronics,8,Technology.EnterpriseIT,3,AffluentInfluential.GeneralInterest.Politics,2
http://redstaplerchronicles.com,Technology.EnterpriseIT,2,Entertainment,2,Lifestyle,2
http://renorealtyblog.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,7,AffluentInfluential.GeneralInterest.Politics,3,AffluentInfluential.Luxury,2
http://reswill806.blogspot.com/,Blog_Does_Not_Exist,7,,,,
http://rivera2007.freeblogit.com,AffluentInfluential.GeneralInterest.Politics,7,,,,
http://rizzn.com/blog/index.php,Technology.Consumer.Electronics,8,AffluentInfluential.GeneralInterest.Politics,3,Lifestyle,2
http://rockinmama.net/,Lifestyle.ParentingFamily,6,Lifestyle.HealthFitnessDiet,2,Lifestyle.BeautyFashion.ShoppingFashion,2
http://ronebreak.com,Entertainment.Celebrities.MoviesTelevisionMusic,7,AffluentInfluential.GeneralInterest.Politics,5,Lifestyle,3
http://ryehemsley.blogspot.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,5,Technology.EnterpriseIT,2,,
http://sadiessay-so.blogspot.com/,Blog_Does_Not_Exist,2,AffluentInfluential.GeneralInterest,2,Lifestyle,2
http://sandrazbuzz.blogspot.com/,Blog_Does_Not_Exist,5,Spam.Blog,2,,
http://santeriareligion101.com/blog,Lifestyle.HealthFitnessDiet,6,,,,
http://santoshibuzz.blogspot.com/,AffluentInfluential.Luxury.Automotive,4,Technology.Consumer,2,Entertainment.Mens.Interest,2
http://saphrym.com/blog,Entertainment.Celebrities.MoviesTelevisionMusic,5,Lifestyle,5,Entertainment.Celebrities.Gossip,3
http://sarahspy.blogspot.com/,Lifestyle,5,Entertainment.Celebrities.Gossip,5,Entertainment.Celebrities.MoviesTelevisionMusic,3
http://savory-bites.com/blog,Lifestyle.HealthFitnessDiet,5,AffluentInfluential.Luxury.FoodWine,4,,
http://scottbuzzles.blogspot.com/,Lifestyle,4,Entertainment,2,,
http://scrappinwithlori.blogspot.com/,AffluentInfluential.ArtsCraftsDesign,4,Lifestyle,4,,
http://seantiner.blogspot.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,Technology.EnterpriseIT,2,Lifestyle,2
http://sectionhiker.com,Entertainment.Sports.AdventureOutdoorSports,6,Lifestyle.HealthFitnessDiet,2,Lifestyle.BeautyFashion.ShoppingFashion,2
http://serial-box.net,Technology.EnterpriseIT,4,Technology.Consumer,3,AffluentInfluential.GeneralInterest,2
http://sesimag.wordpress.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,5,Lifestyle.BeautyFashion.BeautyCosmetics,4,,
http://sethgodin.typepad.com/seths_blog/,Lifestyle.BeautyFashion.ShoppingFashion,8,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,5,Lifestyle.ParentingFamily,4
http://sgtgrumpy.blogspot.com/,AffluentInfluential.GeneralInterest.Politics,3,Entertainment.Mens.Interest,3,Lifestyle,2
http://shoesfromaroundtheglobe.blogspot.com/,Lifestyle.BeautyFashion.ShoppingFashion,8,,,,
http://shortstory.us.com,Entertainment,3,AffluentInfluential.ArtsCraftsDesign,3,AffluentInfluential.GreenLiving,2
http://showmethecurry.com,AffluentInfluential.Luxury.FoodWine,5,Lifestyle.ParentingFamily,2,,
http://simonmak.blogspot.com/,Lifestyle,7,,,,
http://simplebrowser.blogspot.com/,Lifestyle,4,AffluentInfluential.GeneralInterest.Politics,4,Entertainment,2
http://siriusbuzz.com,Technology.Consumer.Electronics,5,Entertainment.Celebrities.MoviesTelevisionMusic,3,,
http://sixpixmix.com/,Entertainment.Celebrities.MoviesTelevisionMusic,6,,,,
http://smartwealthsystem.wordpress.com,Blog_Does_Not_Exist,7,,,,
http://sofhaljamil.com,AffluentInfluential.Travel,4,Lifestyle.ParentingFamily,4,Technology.Consumer,4
http://somenotesonnapkins.blogspot.com/,Lifestyle.BeautyFashion.BeautyCosmetics,7,Lifestyle.BeautyFashion.ShoppingFashion,6,Entertainment.Celebrities,3
http://sonubuzz.blogspot.com/,Lifestyle.ParentingFamily,3,Lifestyle.HealthFitnessDiet,3,AffluentInfluential.Luxury.FoodWine,3
http://southernpreppy.blogspot.com/,Lifestyle.ParentingFamily,8,Lifestyle.BeautyFashion.ShoppingFashion,6,,
http://sparkchasr.blogspot.com/,Blog_Does_Not_Exist,5,,,,
http://sports.outsidethebeltway.com,Entertainment.Sports.CommercialSports,8,,,,
http://sports.rightpundits.com,Entertainment.Celebrities.Gossip,5,Entertainment.Sports.CommercialSports,2,Entertainment.Celebrities.MoviesTelevisionMusic,2
http://startupmeme.com/,Technology.EnterpriseIT,6,Technology.Consumer,4,,
http://street707.blogspot.com/,Technology.Consumer.Electronics,5,Technology.Consumer.Gaming,4,Technology.EnterpriseIT,3
http://structuredsettlements.typepad.com/structured_settlements_4r/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,Spam.Blog,2,,
http://stuffflypeoplelike.com,Lifestyle.BeautyFashion.ShoppingFashion,6,Entertainment.Celebrities.MoviesTelevisionMusic,5,Entertainment.Celebrities.Gossip,4
http://sunshineandlemonade.blogspot.com,Lifestyle.ParentingFamily,7,,,,
http://superfantasticplastic.blogspot.com/,AffluentInfluential.GeneralInterest.Politics,4,Entertainment.Celebrities.MoviesTelevisionMusic,3,Entertainment.Celebrities.Gossip,3
http://supermodels.nl/Pages/Rss.aspx,Entertainment.Celebrities.Gossip,6,,,,
http://sweet-potatopie.blogspot.com/,Lifestyle.HealthFitnessDiet,7,,,,
http://sweet-potatopie.com/,Lifestyle.HealthFitnessDiet,7,,,,
http://takethosepictures.blogspot.com/,Technology.Consumer.Electronics,5,AffluentInfluential.ArtsCraftsDesign,2,Lifestyle,2
http://tanyapeila.blogspot.com/,Lifestyle.ParentingFamily,8,,,,
http://taranfx.blogspot.com/,Technology.Consumer.Gaming,9,Technology.Consumer.Electronics,8,,
http://techjamboree.com,Technology.Consumer.Electronics,8,Technology.EnterpriseIT,4,,
http://techkeyla.com,Technology.Consumer.Electronics,10,Technology.EnterpriseIT,5,,
http://technologyexpert.blogspot.com/,Technology.EnterpriseIT,5,Technology.Consumer,4,,
http://technomom.com,Lifestyle.ParentingFamily,7,Lifestyle.HealthFitnessDiet,4,,
http://techtemper.blogspot.com/,Technology.Consumer.Electronics,10,Technology.EnterpriseIT,4,Entertainment.Celebrities.MoviesTelevisionMusic,2
http://techtoday.110mb.com,Technology.EnterpriseIT,6,Technology.Consumer,4,,
http://teenagesupermodels.blogspot.com/,Blog_Does_Not_Exist,7,,,,
http://terrapixel.wordpress.com,Lifestyle,3,Entertainment,2,,
http://terrobuzz.blogspot.com/,Lifestyle,3,Entertainment.Celebrities.MoviesTelevisionMusic,3,Technology,2
http://test-selenium.blogspot.com/,Technology.EnterpriseIT,6,Technology.Consumer.Electronics,4,,
http://tfav1630frgodbeyjr.blogspot.com/,Entertainment.Celebrities.MoviesTelevisionMusic,8,,,,
http://thatnashvillesound.blogspot.com/,Entertainment.Celebrities.MoviesTelevisionMusic,7,,,,
http://the-writing-bug.blogspot.com/,AffluentInfluential.ArtsCraftsDesign,5,Lifestyle.HealthFitnessDiet,4,AffluentInfluential.GeneralInterest,3
http://thecentsiblesawyer.blogspot.com/,Lifestyle.ParentingFamily,5,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2,,
http://thecollegebaseballblog.com,Entertainment.Sports.CommercialSports,7,,,,
http://theconcretejournal.com/2,Entertainment.Celebrities.MoviesTelevisionMusic,5,Entertainment.Celebrities.Gossip,4,Lifestyle,2
http://thecookmobile.com,AffluentInfluential.Luxury.FoodWine,5,Lifestyle.ParentingFamily,4,,
http://thedailydoozy.com,Blog_Does_Not_Exist,7,,,,
http://thedailywtf.com/,Technology.EnterpriseIT,6,,,,
http://thefestivalhunter.blogspot.com/,Entertainment.Celebrities.MoviesTelevisionMusic,8,,,,
http://thefranchiseking.typepad.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,10,Technology.EnterpriseIT,2,,
http://thegoodfella.typepad.com/the_goodfella/,AffluentInfluential.GeneralInterest.Politics,5,Lifestyle,3,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3
http://thehottestgadgets.com,Technology.Consumer.Electronics,7,Technology.EnterpriseIT,2,,
http://theimperfectmom.com,Lifestyle.ParentingFamily,8,Lifestyle.BeautyFashion,2,,
http://thejoftoday.blogspot.com/,Technology.EnterpriseIT,4,Technology.Consumer,2,,
http://theminorityreportblog.com,AffluentInfluential.GeneralInterest.Politics,6,Entertainment.Celebrities,2,Technology.Consumer.Electronics,2
http://themmazone.net/Martial-Arts-WP,Entertainment.Sports.CommercialSports,4,Entertainment.Sports.AdventureOutdoorSports,4,Lifestyle.HealthFitnessDiet,3
http://themomentrepreneur.blogspot.com/,Lifestyle.ParentingFamily,7,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,7,,
http://thepopculturejunkie.blogspot.com/,Entertainment.Celebrities.Gossip,6,Entertainment.Celebrities.MoviesTelevisionMusic,5,,
http://theprissykitty.com,Blog_Does_Not_Exist,6,,,,
http://thescifiles.blogspot.com/,Technology.EnterpriseIT,5,AffluentInfluential,2,,
http://thesecretofbeauty.blogspot.com/,AffluentInfluential.Travel,4,Lifestyle.BeautyFashion.BeautyCosmetics,4,,
http://thesportsculture.com/,Entertainment.Sports.CommercialSports,6,Entertainment.Celebrities.Gossip,2,,
http://thesportshernia.typepad.com/,Entertainment.Sports.CommercialSports,11,Entertainment.Celebrities.Gossip,3,Entertainment.Mens.Interest,2
http://thestylerules.blogspot.com/,Lifestyle.BeautyFashion.ShoppingFashion,7,AffluentInfluential.ArtsCraftsDesign,2,AffluentInfluential.Luxury,2
http://thetrannydiaries.blogspot.com/,Entertainment.Celebrities.Gossip,3,Lifestyle.BeautyFashion.ShoppingFashion,3,Entertainment.Celebrities.MoviesTelevisionMusic,2
http://thetvaddict.com/,Entertainment.Celebrities.MoviesTelevisionMusic,7,Entertainment.Celebrities.Gossip,3,,
http://thewmblog.com,Technology.EnterpriseIT,3,Spam.Blog,2,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2
http://thinkabdul.com ,Technology.Consumer.Electronics,6,Technology.EnterpriseIT,3,,
http://tightfistedmiser.com,Lifestyle,3,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3,,
http://timmy.vox.com/library/posts/page/1/,Lifestyle.ParentingFamily,5,Entertainment.Celebrities.MoviesTelevisionMusic,3,AffluentInfluential.GeneralInterest.Politics,3
http://timworstall.typepad.com/timworstall/,Entertainment.Celebrities.Gossip,8,AffluentInfluential.GeneralInterest,2,Lifestyle.BeautyFashion.ShoppingFashion,2
http://tipsbytori.blogspot.com/,Lifestyle.BeautyFashion.BeautyCosmetics,7,Lifestyle.BeautyFashion.ShoppingFashion,6,Lifestyle.HealthFitnessDiet,4
http://totalclubfootball.com,Entertainment.Sports.CommercialSports,7,,,,
http://toycarsinmypurse.blogspot.com/,Lifestyle.ParentingFamily,7,,,,
http://traffic2mypage.com,Blog_Does_Not_Exist,7,,,,
http://travelingmamas.com,AffluentInfluential.Travel,6,Lifestyle.ParentingFamily,4,,
http://travelingnetwork.blogspot.com/,AffluentInfluential.Travel,7,,,,
http://trueleo.blogspot.com/,Lifestyle.HealthFitnessDiet,5,Entertainment.Celebrities.MoviesTelevisionMusic,4,,
http://tv.rightcelebrity.com,Entertainment.Celebrities.MoviesTelevisionMusic,8,Entertainment.Celebrities.Gossip,7,,
http://txpress.blogspot.com/,Technology.Consumer.Electronics,11,,,,
http://txwineblog.blogspot.com/,Blog_Does_Not_Exist,6,,,,
http://ubringmejoi.blogspot.com/,Entertainment.Celebrities.MoviesTelevisionMusic,5,Lifestyle.BeautyFashion,5,Entertainment.Celebrities.Gossip,5
http://uponregistration.com,Technology.EnterpriseIT,6,,,,
http://urdirt.blogspot.com/,Entertainment.Sports.CommercialSports,11,Entertainment.Celebrities.MoviesTelevisionMusic,3,Entertainment.Mens.Interest,3
http://varsitylecture.com,Technology.EnterpriseIT,6,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2,,
http://verygoodtips.com,Lifestyle.HealthFitnessDiet,4,AffluentInfluential,2,Lifestyle.ParentingFamily,2
http://viewpointjournal.com,AffluentInfluential.GeneralInterest.Politics,7,,,,
http://virtualmerchants.blogspot.com/,Technology.Consumer.Gaming,4,Technology.Consumer.Electronics,4,Technology.EnterpriseIT,2
http://watch-weeds-online.org,Entertainment.Sports.AdventureOutdoorSports,8,Entertainment.Celebrities.MoviesTelevisionMusic,8,,
http://webabout.org,Technology.EnterpriseIT,7,Technology.Consumer,7,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2
http://webatlantis.org,Technology.EnterpriseIT,5,AffluentInfluential.GeneralInterest.Politics,2,,
http://webgems.squarespace.com/blog/,Lifestyle.BeautyFashion.ShoppingFashion,7,AffluentInfluential.ArtsCraftsDesign,3,Lifestyle.ParentingFamily,3
http://webtoolsandtips.com,Technology.EnterpriseIT,7,,,,
http://westthoughts.blogspot.com/,Blog_Does_Not_Exist,6,,,,
http://whatscooking.us,Lifestyle.HealthFitnessDiet,3,AffluentInfluential.Luxury.FoodWine,3,,
http://wideworldofwasser.blogspot.com/,Lifestyle,6,,,,
http://wiflba.com,AffluentInfluential.GeneralInterest,4,Technology.Consumer.Gaming,4,Technology.Consumer.Electronics,4
http://winecask.blogspot.com,AffluentInfluential.Luxury.FoodWine,9,,,,
http://wirelessandmobilenews.com/ ,Technology.Consumer.Electronics,7,,,,
http://withoutanoilwell.blogspot.com/,AffluentInfluential.GeneralInterest.Politics,7,,,,
http://womenslegalresource.com/blog,AffluentInfluential.GeneralInterest.Politics,5,Lifestyle.ParentingFamily,2,,
http://writer.fitzhome.com,Entertainment.Celebrities.MoviesTelevisionMusic,7,Technology.Consumer.Electronics,2,,
http://writingnag.blogspot.com/,AffluentInfluential.ArtsCraftsDesign,4,Lifestyle,4,,
http://wtfurls.com/,Entertainment.Celebrities.Gossip,5,Technology.Consumer.Gaming,2,AffluentInfluential.GeneralInterest.Politics,2
http://www.101greatgoals.com/,Entertainment.Sports.CommercialSports,10,,,,
http://www.707ave.com,Entertainment.Celebrities.MoviesTelevisionMusic,5,AffluentInfluential.Travel,2,AffluentInfluential.ArtsCraftsDesign,2
http://www.Bark-N-Blog.com,Lifestyle.BeautyFashion,6,AffluentInfluential.GreenLiving,3,,
http://www.FatManUnleashed.com,Lifestyle.HealthFitnessDiet,8,,,,
http://www.achicplace.com/,Lifestyle.BeautyFashion.ShoppingFashion,7,Lifestyle.BeautyFashion.BeautyCosmetics,5,,
http://www.actresssnaps.com/,Entertainment.Celebrities.Gossip,7,Entertainment.Celebrities.MoviesTelevisionMusic,3,,
http://www.adesblog.com,Technology.EnterpriseIT,4,Technology.Consumer.Electronics,4,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3
http://www.adsense-pro.com,Technology.EnterpriseIT,7,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2,,
http://www.adverbox.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,Entertainment.Celebrities.MoviesTelevisionMusic,3,Technology.Consumer,2
http://www.alabamagameday.net/,Entertainment.Sports.CommercialSports,8,,,,
http://www.albertanaya.com,Entertainment.Sports.CommercialSports,7,Lifestyle,2,AffluentInfluential.GeneralInterest.Politics,2
http://www.alleyinsider.com/,Technology.Consumer.Electronics,6,Technology.EnterpriseIT,4,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4
http://www.amamasrant.com/a_mamas_rant/,Lifestyle.ParentingFamily,8,Lifestyle.HealthFitnessDiet,4,Lifestyle.BeautyFashion,3
http://www.andersonfreepress.net,AffluentInfluential.GeneralInterest.Politics,8,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,,
http://www.animecrunch.com,Entertainment.Celebrities.MoviesTelevisionMusic,6,,,,
http://www.arcade-renaissance.com/,Technology.Consumer.Gaming,7,,,,
http://www.arkst.com,Entertainment.Sports.CommercialSports,7,,,,
http://www.b-townblog.com,AffluentInfluential.GeneralInterest.Politics,9,Entertainment.Celebrities.MoviesTelevisionMusic,4,Lifestyle,2
http://www.babyblogaddict.com/,Lifestyle.ParentingFamily,7,,,,
http://www.babyfirstyear.org/,Lifestyle.ParentingFamily,5,,,,
http://www.baekdal.com,Technology.Consumer.Electronics,5,Lifestyle.BeautyFashion,4,,
http://www.bannedinhollywood.com,Entertainment.Celebrities.Gossip,5,Entertainment.Mens.Interest,3,,
http://www.barkbiteblog.com/,Entertainment.Celebrities.Gossip,6,Entertainment.Celebrities.MoviesTelevisionMusic,5,,
http://www.beechin.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,10,,,,
http://www.beijingolympicsfan.com,Entertainment.Sports.CommercialSports,5,Entertainment.Sports.AdventureOutdoorSports,3,AffluentInfluential.GeneralInterest.Politics,2
http://www.berryreporter.com,Technology.Consumer.Electronics,6,,,,
http://www.betterthanabusinesscard.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,6,Technology.EnterpriseIT,2,,
http://www.bigpawblog.com/,Lifestyle,6,,,,
http://www.bigredkitchen.com/,Lifestyle.ParentingFamily,3,AffluentInfluential.Luxury.FoodWine,3,Lifestyle.HealthFitnessDiet,2
http://www.bikerholics.com,Blog_Does_Not_Exist,7,,,,
http://www.bloggingtips.com,Technology.EnterpriseIT,6,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,,
http://www.bobbiedawn.com/,Entertainment.Mens.Interest,5,Lifestyle.BeautyFashion,2,,
http://www.bobreyes.com/myblog,Entertainment.Celebrities.MoviesTelevisionMusic,7,Entertainment.Celebrities.Gossip,3,Technology.Consumer.Electronics,2
http://www.bostonmamas.com/,Lifestyle.ParentingFamily,7,Lifestyle.HealthFitnessDiet,3,Lifestyle.BeautyFashion.ShoppingFashion,3
http://www.brentter.com,Entertainment.Sports,3,Lifestyle,3,AffluentInfluential.GeneralInterest.Politics,3
http://www.brideplanswedding.com/blog/,Lifestyle.ParentingFamily,6,Lifestyle.BeautyFashion.BeautyCosmetics,5,Lifestyle.BeautyFashion.ShoppingFashion,5
http://www.britneyspears.com/,Entertainment.Celebrities.Gossip,8,Entertainment.Celebrities.MoviesTelevisionMusic,6,,
http://www.brokegradstudent.com,Lifestyle.ParentingFamily,6,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2,,
http://www.brubakers.us/foodies,AffluentInfluential.Luxury.FoodWine,4,Lifestyle.HealthFitnessDiet,3,,
http://www.bustedcoverage.com,Entertainment.Sports,3,Entertainment.Mens.Interest,3,Entertainment.Celebrities,2
http://www.buzzlogic.com/productdemo/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3,Technology.EnterpriseIT,2,Technology.Consumer,2
http://www.buzzlogic.com/time/b6/,Technology.EnterpriseIT,6,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3,AffluentInfluential.GeneralInterest.Politics,2
http://www.buzzpirates.com,Entertainment.Mens.Interest,5,Entertainment.Celebrities.MoviesTelevisionMusic,4,AffluentInfluential.GeneralInterest.Politics,3
http://www.celebritybeautybuzz.com,Entertainment.Celebrities.Gossip,7,Entertainment.Celebrities.MoviesTelevisionMusic,5,Lifestyle.BeautyFashion.BeautyCosmetics,4
http://www.chrisd.ca/blog,AffluentInfluential.GeneralInterest.Politics,7,,,,
http://www.chrisheuer.com,Lifestyle,3,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3,Technology.Consumer,2
http://www.christianpf.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,Lifestyle,3,,
http://www.cleverwittyquick.com/,Technology.EnterpriseIT,4,Technology.Consumer.Electronics,4,Entertainment,2
http://www.cliqueclack.com/tv/,Entertainment.Celebrities.MoviesTelevisionMusic,7,,,,
http://www.closettherapyblog.com,Lifestyle.BeautyFashion.ShoppingFashion,8,Lifestyle.BeautyFashion.BeautyCosmetics,5,,
http://www.coffeewithrich.com/,Blog_Does_Not_Exist,7,,,,
http://www.collegefinance101.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,5,Lifestyle.ParentingFamily,4,,
http://www.conversationalmediamarketing.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,Technology.EnterpriseIT,3,,
http://www.countrymusicislove.com/,Entertainment.Celebrities.MoviesTelevisionMusic,7,,,,
http://www.crazytrike.com,Lifestyle.HealthFitnessDiet,3,Entertainment.Sports.AdventureOutdoorSports,2,,
http://www.cssnewbie.com,Technology.EnterpriseIT,5,Technology.Consumer.Electronics,5,Lifestyle,2
http://www.culturefeast.com,Entertainment.Celebrities.Gossip,6,Entertainment.Celebrities.MoviesTelevisionMusic,5,Lifestyle,3
http://www.dacari.net/,AffluentInfluential.Luxury.Automotive,6,Entertainment.Mens.Interest,2,,
http://www.daemonstv.com,Entertainment.Celebrities.MoviesTelevisionMusic,8,Entertainment.Celebrities.Gossip,2,,
http://www.dailyfungo.com,Entertainment.Sports.CommercialSports,8,,,,
http://www.darrensessions.com,Technology.Consumer,6,Technology.EnterpriseIT,5,,
http://www.davechung.com,Entertainment.Celebrities.MoviesTelevisionMusic,6,Entertainment.Celebrities.Gossip,6,Entertainment.Sports.CommercialSports,3
http://www.dayseeker.com,Lifestyle.HealthFitnessDiet,9,Lifestyle.BeautyFashion.BeautyCosmetics,3,,
http://www.denimology.co.uk/,Lifestyle.BeautyFashion.ShoppingFashion,7,,,,
http://www.derrickdonald.com/my_weblog/,AffluentInfluential.GeneralInterest.Politics,7,,,,
http://www.designvitality.com/blog,Technology.EnterpriseIT,5,Technology.Consumer,5,AffluentInfluential.ArtsCraftsDesign,3
http://www.distressedvolatility.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,6,AffluentInfluential.GeneralInterest.Politics,2,,
http://www.dividends4life.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,6,,,,
http://www.djmick.co.uk/latest,Entertainment.Celebrities.Gossip,8,Entertainment.Celebrities.MoviesTelevisionMusic,5,Entertainment.Mens.Interest,3
http://www.dodevice.com/,Technology.Consumer.Electronics,12,Technology.EnterpriseIT,3,,
http://www.dohiyimir.org/,AffluentInfluential.GeneralInterest.Politics,6,Lifestyle,3,,
http://www.dorynsdish.com/,Lifestyle.ParentingFamily,6,Lifestyle.BeautyFashion.BeautyCosmetics,3,Lifestyle.BeautyFashion.ShoppingFashion,3
http://www.draculavseisenstein.com,AffluentInfluential.ArtsCraftsDesign,3,Lifestyle.BeautyFashion,3,,
http://www.drinkoftheweek.com/blog,AffluentInfluential.Luxury.FoodWine,10,,,,
http://www.duckeldanny.com,Technology,5,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,,
http://www.ecmstrategy.com/is/,Technology.EnterpriseIT,6,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2,,
http://www.emergiblog.com,Lifestyle.HealthFitnessDiet,5,AffluentInfluential.GeneralInterest,3,,
http://www.emqb.com,Entertainment.Sports.CommercialSports,6,,,,
http://www.epiccarnival.com/,Entertainment.Sports.CommercialSports,7,Entertainment.Celebrities.Gossip,4,Entertainment.Celebrities.MoviesTelevisionMusic,2
http://www.epltalk.com/,Entertainment.Sports.CommercialSports,6,,,,
http://www.expiredfoods.com/,AffluentInfluential.Luxury.FoodWine,4,Lifestyle.HealthFitnessDiet,2,,
http://www.fantasybaseballflash.com,Entertainment.Sports.CommercialSports,8,,,,
http://www.feedbytes.com,Technology.EnterpriseIT,5,Technology.Consumer,3,AffluentInfluential.GreenLiving,2
http://www.findableblogs.com,Technology.Consumer,6,,,,
http://www.fitness-equipment-solutions.com,Lifestyle.HealthFitnessDiet,7,,,,
http://www.floridabits.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,AffluentInfluential.GeneralInterest.Politics,3,,
http://www.floridaventureblog.com/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,5,AffluentInfluential.GeneralInterest.Politics,2,,
http://www.foozoodesign.com/blog,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,Technology.EnterpriseIT,2,AffluentInfluential.ArtsCraftsDesign,2
http://www.frugalmama.org,Lifestyle.ParentingFamily,6,Lifestyle.HealthFitnessDiet,2,,
http://www.futurenerd.net,Technology.Consumer.Electronics,13,Technology.EnterpriseIT,6,AffluentInfluential.GeneralInterest.Politics,5
http://www.gadgetvenue.com/ ,Technology.Consumer.Electronics,9,Technology.Consumer.Gaming,4,,
http://www.gamjams.net/,Entertainment.Sports.AdventureOutdoorSports,8,,,,
http://www.ghacks.net/,Technology.Consumer.Electronics,8,Technology.EnterpriseIT,4,,
http://www.glamboulevard.com,Blog_Does_Not_Exist,7,,,,
http://www.glamorousbee.com/,Lifestyle.BeautyFashion.BeautyCosmetics,8,Lifestyle.BeautyFashion.ShoppingFashion,5,,
http://www.halohalo.ph/wordpress,Lifestyle,5,Entertainment.Celebrities.MoviesTelevisionMusic,4,AffluentInfluential.ArtsCraftsDesign,2
http://www.hipgirlie.com,Lifestyle.BeautyFashion.BeautyCosmetics,7,Lifestyle.BeautyFashion.ShoppingFashion,6,,
http://www.holycool.net/,AffluentInfluential.ArtsCraftsDesign,5,Lifestyle,3,,
http://www.homebbq.com,Lifestyle.HealthFitnessDiet,5,Lifestyle.ParentingFamily,3,AffluentInfluential.Luxury.FoodWine,2
http://www.homeconstructionimprovement.com/,AffluentInfluential.ArtsCraftsDesign,4,Lifestyle.ParentingFamily,3,,
http://www.hostscope.com,Technology.EnterpriseIT,7,Technology.Consumer,4,,
http://www.hswrestling.net,Entertainment.Sports.CommercialSports,9,,,,
http://www.idiotsguidetoblogging.com/,Technology.EnterpriseIT,6,Technology.Consumer,6,,
http://www.iheartthat.com,Entertainment.Celebrities.Gossip,6,Lifestyle.BeautyFashion.ShoppingFashion,6,Entertainment.Celebrities.MoviesTelevisionMusic,4
http://www.inquisitr.com,Entertainment.Celebrities.Gossip,6,AffluentInfluential.GeneralInterest.Politics,5,Entertainment.Celebrities.MoviesTelevisionMusic,4
http://www.iphonefirmware.com,Technology.Consumer.Electronics,7,,,,
http://www.joetech.com,Technology.Consumer.Electronics,8,Technology.Consumer.Gaming,5,Technology.EnterpriseIT,2
http://www.jophilsuperman.com,Lifestyle,5,AffluentInfluential.Travel,3,AffluentInfluential.GeneralInterest.Politics,3
http://www.karthikeyan.net.in/,AffluentInfluential.GeneralInterest.Politics,4,Entertainment.Celebrities.MoviesTelevisionMusic,3,Lifestyle,2
http://www.kenswineguide.com,AffluentInfluential.Luxury.FoodWine,10,,,,
http://www.lahrweb.com/,Technology.EnterpriseIT,6,,,,
http://www.liewcf.com/,Technology.Consumer.Electronics,6,,,,
http://www.lisacwrites.com/,Lifestyle.ParentingFamily,6,AffluentInfluential.GeneralInterest,2,,
http://www.livegrids.net,Entertainment.Mens.Interest,5,Technology,3,AffluentInfluential.Luxury.Automotive,2
http://www.loadedgunboston.com/,Entertainment.Celebrities.Gossip,6,Entertainment.Celebrities.MoviesTelevisionMusic,4,,
http://www.looktothestars.org,Entertainment.Celebrities.Gossip,8,,,,
http://www.madisonwhitney.com/wordpress,Lifestyle.HealthFitnessDiet,6,,,,
http://www.mamadivas.com,Lifestyle.ParentingFamily,6,Entertainment.Celebrities.MoviesTelevisionMusic,2,Entertainment.Celebrities.Gossip,2
http://www.mamalisa.com/,Lifestyle.ParentingFamily,6,,,,
http://www.marketingwicked.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,7,Technology.EnterpriseIT,3,,
http://www.materialicious.com/,AffluentInfluential.ArtsCraftsDesign,3,Lifestyle,2,,
http://www.michaelaulia.com/blogs,Technology.Consumer.Electronics,6,Technology.EnterpriseIT,3,Technology.Consumer.Gaming,3
http://www.missingsaddle.com,Entertainment.Sports.AdventureOutdoorSports,7,,,,
http://www.mls-rumors.net/,Entertainment.Sports.CommercialSports,8,,,,
http://www.mobilecrunch.com/,Technology.Consumer.Electronics,8,,,,
http://www.mobilegamefaqs.com/index.php,Technology.Consumer.Gaming,9,,,,
http://www.moderndesignblog.com/,AffluentInfluential.Luxury,4,Lifestyle.BeautyFashion.ShoppingFashion,3,AffluentInfluential.ArtsCraftsDesign,2
http://www.mommieswithstyle.com/mtblog/,Lifestyle.ParentingFamily,4,Lifestyle.BeautyFashion.BeautyCosmetics,4,Lifestyle.BeautyFashion.ShoppingFashion,4
http://www.momshomerecipes.com,Lifestyle.HealthFitnessDiet,5,Lifestyle.ParentingFamily,3,AffluentInfluential.Luxury.FoodWine,2
http://www.moodraiser.com/,Lifestyle.HealthFitnessDiet,6,,,,
http://www.moonbattery.com/,AffluentInfluential.GeneralInterest.Politics,6,,,,
http://www.musicalentrepreneur.com/musical_entrepreneur/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,7,Entertainment.Celebrities.MoviesTelevisionMusic,3,Technology.EnterpriseIT,2
http://www.musicloversanonymous.com/,Entertainment.Celebrities.MoviesTelevisionMusic,7,,,,
http://www.mwgamer.com,Blog_Does_Not_Exist,5,,,,
http://www.mynetbizz.com/travelweb,AffluentInfluential.Travel,6,,,,
http://www.myopenwallet.net/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,5,Lifestyle,4,AffluentInfluential.GeneralInterest.Politics,2
http://www.myreadablefeast.com,Lifestyle.ParentingFamily,6,Entertainment.Celebrities.MoviesTelevisionMusic,2,,
http://www.mytwodollars.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,10,AffluentInfluential.GeneralInterest.Politics,6,Lifestyle,2
http://www.naphe.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,7,AffluentInfluential.GeneralInterest.Politics,2,,
http://www.nashvillegab.com/,Entertainment.Celebrities.MoviesTelevisionMusic,6,Entertainment.Celebrities.Gossip,6,,
http://www.nashvillenarc.com/,Entertainment.Celebrities.MoviesTelevisionMusic,6,Entertainment.Celebrities.Gossip,3,,
http://www.nationalterroralert.com,AffluentInfluential.GeneralInterest.Politics,9,Technology,2,,
http://www.nepatriotsdraft.com/,Entertainment.Sports.CommercialSports,7,,,,
http://www.netfamilynews.org/index.shtml,AffluentInfluential.GeneralInterest.Politics,6,Lifestyle.ParentingFamily,5,Technology.Consumer,4
http://www.notsoboringlife.com,Lifestyle,5,AffluentInfluential.ArtsCraftsDesign,2,Entertainment.Sports.AdventureOutdoorSports,2
http://www.obscanity.com,AffluentInfluential.GeneralInterest.Politics,6,Entertainment,2,,
http://www.oddpodz.com/blog/index.php,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,6,Technology.EnterpriseIT,2,,
http://www.oddseo.com/,Technology.EnterpriseIT,4,Technology.Consumer,2,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2
http://www.onebigdog.net/,AffluentInfluential.GeneralInterest.Politics,6,,,,
http://www.onecore.net,Technology.EnterpriseIT,6,Technology.Consumer.Electronics,3,,
http://www.onlocationvacations.com,AffluentInfluential.Travel,6,Entertainment.Celebrities.MoviesTelevisionMusic,3,,
http://www.ordinarylivingextraordinary.com/the_extraordinary_life_of/,Lifestyle.ParentingFamily,7,,,,
http://www.organizedchristmas.com,Lifestyle.ParentingFamily,7,AffluentInfluential.ArtsCraftsDesign,2,,
http://www.osx-e.com,Technology.Consumer.Electronics,5,Technology.EnterpriseIT,2,,
http://www.outsidethebeltway.com,AffluentInfluential.GeneralInterest.Politics,6,,,,
http://www.pajamadeen.com,AffluentInfluential.GeneralInterest.Politics,6,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3,Entertainment,2
http://www.pajiba.com/,Entertainment.Celebrities.MoviesTelevisionMusic,7,,,,
http://www.paralegalsblog.com/,AffluentInfluential.GeneralInterest.Politics,9,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,7,,
http://www.parentssupportnetwork.com/p2p,Lifestyle.ParentingFamily,7,,,,
http://www.passionateamerica.com,AffluentInfluential.GeneralInterest.Politics,6,Lifestyle.HealthFitnessDiet,2,,
http://www.pauldesousa.co.za,Technology.Consumer.Electronics,7,AffluentInfluential.GeneralInterest.Politics,5,Lifestyle,4
http://www.peanutallergykid.com/,Lifestyle.ParentingFamily,6,Lifestyle.HealthFitnessDiet,6,,
http://www.photoshoplady.com,Technology.Consumer.Electronics,11,Technology.EnterpriseIT,4,AffluentInfluential.ArtsCraftsDesign,3
http://www.pingable.org,Technology.EnterpriseIT,5,Technology.Consumer,3,,
http://www.pinstripemag.com/home/,Lifestyle.BeautyFashion.ShoppingFashion,7,Entertainment.Mens.Interest,3,,
http://www.popcultureshock.com,Entertainment.Celebrities.MoviesTelevisionMusic,9,Technology.Consumer.Gaming,3,,
http://www.popculturetees.com,Lifestyle.BeautyFashion.ShoppingFashion,5,Entertainment,2,,
http://www.poshlifeposhstyle.com/,Lifestyle.BeautyFashion.BeautyCosmetics,6,Lifestyle.HealthFitnessDiet,5,AffluentInfluential.ArtsCraftsDesign,2
http://www.postcardsfromthefunnyfarm.com,Lifestyle,6,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3,,
http://www.prettymuchamazing.com,Entertainment.Celebrities.MoviesTelevisionMusic,7,,,,
http://www.problogineer.com,Technology.EnterpriseIT,6,Technology.Consumer.Electronics,4,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2
http://www.psymania.com/,Entertainment.Celebrities.MoviesTelevisionMusic,6,,,,
http://www.pukingdog.com/,Entertainment,4,AffluentInfluential.GeneralInterest.Politics,3,Lifestyle,2
http://www.randyzlobec.com,Technology.EnterpriseIT,5,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2,,
http://www.readwriteweb.com/,Technology.Consumer,6,,,,
http://www.redcarpet-fashionawards.com/,Lifestyle.BeautyFashion.ShoppingFashion,6,Entertainment.Celebrities.Gossip,4,,
http://www.redferret.net/ ,Technology.Consumer.Electronics,13,,,,
http://www.renodiscontent.com,AffluentInfluential.GeneralInterest.Politics,10,,,,
http://www.rickey.org/,Entertainment.Celebrities.MoviesTelevisionMusic,5,Entertainment.Celebrities.Gossip,5,AffluentInfluential.GeneralInterest.Politics,2
http://www.riehlworldview.com/carnivorous_conservative/,AffluentInfluential.GeneralInterest.Politics,7,,,,
http://www.rightpundits.com,AffluentInfluential.GeneralInterest.Politics,7,,,,
http://www.robertsandie.com,Blog_Does_Not_Exist,7,,,,
http://www.rockfuse.com/blog,Technology.EnterpriseIT,5,Technology.Consumer.Electronics,3,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2
http://www.roloffsonline.com/,Entertainment.Celebrities.MoviesTelevisionMusic,7,,,,
http://www.runningandrambling.com/,Entertainment.Sports.AdventureOutdoorSports,6,Lifestyle.HealthFitnessDiet,6,Entertainment.Celebrities.MoviesTelevisionMusic,3
http://www.saadkamal.com,Technology.EnterpriseIT,6,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,Technology.Consumer,3
http://www.seanpaune.com,Technology.Consumer.Electronics,10,Lifestyle,4,Entertainment.Celebrities.Gossip,3
http://www.sensiblelivings.com,Blog_Does_Not_Exist,7,,,,
http://www.sergetheconcierge.com/,Technology.Consumer,4,Entertainment,3,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3
http://www.sexonthebeachmag.com,Lifestyle,3,Blog_Does_Not_Exist,2,Entertainment.Mens.Interest,2
http://www.shivae.net,Entertainment.Celebrities.MoviesTelevisionMusic,4,AffluentInfluential.ArtsCraftsDesign,2,,
http://www.shrinkingsisters.com/,Lifestyle.HealthFitnessDiet,7,,,,
http://www.simplemarriage.net,Lifestyle.ParentingFamily,6,,,,
http://www.sini.net,Technology.Consumer.Electronics,9,Technology.EnterpriseIT,4,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2
http://www.sisterlysavings.net/,Lifestyle.ParentingFamily,6,Lifestyle.HealthFitnessDiet,5,,
http://www.sizlopedia.com,Technology.EnterpriseIT,6,Technology.Consumer,5,,
http://www.skineficial.com/blog.html,Lifestyle.BeautyFashion.BeautyCosmetics,6,Lifestyle.HealthFitnessDiet,2,,
http://www.skinnyvscurvy.com,Entertainment.Celebrities.Gossip,6,Lifestyle.HealthFitnessDiet,2,,
http://www.skinsbandwagon.net/content/index.php,Entertainment.Sports.CommercialSports,11,,,,
http://www.smallhousestyle.com,AffluentInfluential.GreenLiving,4,Lifestyle,3,AffluentInfluential.ArtsCraftsDesign,2
http://www.smalltownshopaholic.com/,Lifestyle.BeautyFashion.ShoppingFashion,7,Lifestyle.BeautyFashion.BeautyCosmetics,2,,
http://www.smartadmin.in/,Technology.Consumer.Electronics,12,Technology.EnterpriseIT,7,,
http://www.sodblog.com,AffluentInfluential.GeneralInterest.Politics,5,Entertainment.Sports.CommercialSports,2,,
http://www.staralicious.com,Entertainment.Celebrities.Gossip,9,Lifestyle.BeautyFashion.ShoppingFashion,2,,
http://www.steadyburn.net/,Entertainment.Celebrities,2,Entertainment.Sports,2,Lifestyle,2
http://www.steverenner.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,5,Technology.EnterpriseIT,3,,
http://www.stocktradingtogo.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,7,,,,
http://www.stoptheaclu.com,AffluentInfluential.GeneralInterest.Politics,7,,,,
http://www.suckystuff.net/,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,Lifestyle.BeautyFashion.ShoppingFashion,4,AffluentInfluential.GeneralInterest.Politics,3
http://www.sweethacks.com,Technology.Consumer.Electronics,13,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2,,
http://www.syndicatedelitist.com/,AffluentInfluential.GeneralInterest.Politics,5,Technology,4,Entertainment.Celebrities.MoviesTelevisionMusic,2
http://www.tanyetta.com/,Lifestyle.ParentingFamily,6,AffluentInfluential.GeneralInterest,2,,
http://www.taylorwilsdon.com,Technology.Consumer.Electronics,7,Technology.EnterpriseIT,4,,
http://www.teach42.com,Technology.Consumer.Electronics,10,Lifestyle.ParentingFamily,3,,
http://www.techbanyan.com,AffluentInfluential.GeneralInterest.Politics,4,Entertainment.Celebrities.Gossip,4,Technology.Consumer,3
http://www.techcrunch.com,Technology.Consumer,6,Technology.EnterpriseIT,5,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,3
http://www.techeblog.com/,Technology.Consumer.Electronics,11,Technology.Consumer.Gaming,8,,
http://www.techpavan.com,Technology.EnterpriseIT,5,Technology.Consumer,5,,
http://www.techsnack.net,Technology.Consumer,6,Technology.EnterpriseIT,3,,
http://www.techvivo.com,Technology.EnterpriseIT,6,Technology.Consumer.Electronics,3,,
http://www.teknobites.com,Technology.EnterpriseIT,6,Technology.Consumer,4,,
http://www.the700level.com/,Entertainment.Sports.CommercialSports,10,,,,
http://www.the9513.com/,Entertainment.Celebrities.MoviesTelevisionMusic,6,,,,
http://www.theanand.com/blog,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,Technology.EnterpriseIT,3,Technology.Consumer,2
http://www.theangryt.com,Entertainment.Celebrities.Gossip,5,,,,
http://www.thebargainqueen.com/,Lifestyle.BeautyFashion.ShoppingFashion,7,,,,
http://www.thechocolistas.com/,AffluentInfluential.Luxury.FoodWine,7,Lifestyle,2,,
http://www.thedigeratilife.com/blog,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,8,AffluentInfluential.GeneralInterest.Politics,4,Lifestyle.ParentingFamily,2
http://www.theexpressionist.com,Entertainment.Celebrities.MoviesTelevisionMusic,5,Entertainment.Celebrities.Gossip,4,AffluentInfluential.ArtsCraftsDesign,2
http://www.themommyinsider.typepad.com/,Lifestyle.ParentingFamily,7,,,,
http://www.thenoseonyourface.com,AffluentInfluential.GeneralInterest.Politics,4,Entertainment,3,,
http://www.thequestforit.com/the_quest_for_it/,Lifestyle.BeautyFashion.ShoppingFashion,8,Lifestyle.BeautyFashion.BeautyCosmetics,7,Entertainment.Celebrities,3
http://www.theresabloginmysoup.com,Technology,3,Lifestyle.BeautyFashion.ShoppingFashion,2,,
http://www.thesportsdollar.com/,Entertainment.Sports.CommercialSports,7,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2,,
http://www.thesunsfinancialdiary.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,7,,,,
http://www.theworldofisaac.com/,Entertainment.Mens.Interest,6,Entertainment.Sports.CommercialSports,5,Entertainment.Celebrities,3
http://www.thisis50.com,Entertainment.Celebrities.MoviesTelevisionMusic,7,Entertainment.Celebrities.Gossip,4,Entertainment.Mens.Interest,3
http://www.thismamacooks.com/,Lifestyle.HealthFitnessDiet,6,AffluentInfluential.Luxury.FoodWine,3,,
http://www.timetobudget.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,6,,,,
http://www.tiricosuave.com/,Entertainment.Sports.CommercialSports,4,Entertainment.Celebrities,3,Entertainment.Mens.Interest,2
http://www.tom-hanna.org,AffluentInfluential.GeneralInterest.Politics,6,,,,
http://www.tothepc.com,Technology.Consumer,5,Technology.EnterpriseIT,2,,
http://www.touchpodium.com,Technology.Consumer.Electronics,7,Technology.Consumer.Gaming,2,,
http://www.toycyte.com,Entertainment.Mens.Interest,3,Lifestyle.ParentingFamily,2,Technology.Consumer.Electronics,2
http://www.tranism.com/weblog/,Technology.Consumer.Gaming,7,Technology.Consumer.Electronics,7,Entertainment.Celebrities.MoviesTelevisionMusic,4
http://www.trenddistrict.com/,Lifestyle.BeautyFashion.ShoppingFashion,10,AffluentInfluential.Luxury,2,,
http://www.tropicofmom.com/,Lifestyle.ParentingFamily,5,AffluentInfluential.Travel,2,,
http://www.uberreview.com,Technology.Consumer.Electronics,6,Technology.Consumer.Gaming,5,,
http://www.uncoached.com/,Entertainment.Mens.Interest,5,Entertainment.Celebrities.Gossip,2,,
http://www.unscrewingtheinscrutable.com,Lifestyle,5,AffluentInfluential.GeneralInterest.Politics,3,,
http://www.upscaleswagger.com,Entertainment.Celebrities.Gossip,4,Lifestyle.BeautyFashion.ShoppingFashion,4,Entertainment.Celebrities.MoviesTelevisionMusic,2
http://www.usapresidentmccain.com/,AffluentInfluential.GeneralInterest.Politics,7,,,,
http://www.uyasar.org,Lifestyle.HealthFitnessDiet,8,,,,
http://www.vegasinsight.net,Lifestyle.HealthFitnessDiet,3,AffluentInfluential.GeneralInterest.Politics,3,AffluentInfluential.Travel,2
http://www.veidt.com,Entertainment.Celebrities.MoviesTelevisionMusic,6,,,,
http://www.vinodksingh.com/,Technology.EnterpriseIT,6,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,2,,
http://www.viooli.com/blog,Technology.Consumer.Electronics,5,Technology.EnterpriseIT,2,,
http://www.viralblog.com,Technology.EnterpriseIT,4,Technology.Consumer,4,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4
http://www.virtualizationteam.com,Technology.Consumer.Electronics,6,Technology.EnterpriseIT,5,,
http://www.warrenandderrick.com/,Entertainment.Celebrities.Gossip,7,Entertainment.Celebrities.MoviesTelevisionMusic,3,Lifestyle,2
http://www.weareneverfull.com,AffluentInfluential.Luxury.FoodWine,5,Lifestyle.HealthFitnessDiet,3,,
http://www.webanalyticsbook.com,Blog_Does_Not_Exist,5,Technology,2,,
http://www.webappers.com,Technology.EnterpriseIT,6,Technology.Consumer,3,AffluentInfluential.Travel,2
http://www.webcampuz.com/dashboard,Blog_Does_Not_Exist,3,Lifestyle.ParentingFamily,2,,
http://www.webmetricsguru.com,Technology.EnterpriseIT,7,Technology.Consumer.Electronics,2,,
http://www.whatsthiswebthing.com,Technology.EnterpriseIT,4,Technology.Consumer.Gaming,3,Technology.Consumer.Electronics,3
http://www.wisebread.com/home,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,6,Lifestyle.ParentingFamily,2,,
http://www.wisestartupblog.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,4,Technology.EnterpriseIT,3,Technology.Consumer,3
http://www.wittysparks.com,Technology.Consumer,5,Lifestyle,4,Entertainment.Celebrities.MoviesTelevisionMusic,4
http://www.workexp.com,AffluentInfluential.GeneralInterest.BusinessFinanceInvesting,5,AffluentInfluential.Luxury.Automotive,3,AffluentInfluential.GeneralInterest.Politics,3
http://www.yosemiteblog.com,AffluentInfluential.Travel,6,Lifestyle,3,,
http://www.zestypress.com/,AffluentInfluential.GeneralInterest.Politics,7,Lifestyle,2,,
http://yeeeah.com,Entertainment.Celebrities.Gossip,7,Entertainment.Mens.Interest,2,Lifestyle.BeautyFashion.BeautyCosmetics,2
http://yepyep.gibbs12.com/,Entertainment.Celebrities.MoviesTelevisionMusic,5,Entertainment.Sports,4,Lifestyle.ParentingFamily,3
http://youbeenblinded.com,Entertainment.Sports.CommercialSports,6,Entertainment.Sports.AdventureOutdoorSports,2,,
http://yougotjack.blogspot.com/,Blog_Does_Not_Exist,7,,,,
